WIP Calculs bilans et renvoie JSON
NutriMeal/nutrimeal pull request #3
Opened 2018-04-26 08:24 UTC by Shingo76

2018-04-29 13:38 UTC, clement-bey-cgi requested changes

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/controller/ExportBilanController.java
> +public class ExportBilanController {
t'as fait un exportBilanController --> or on va peut être avoir à exporter d'autre choses (par exemple un export PDF d'une recette avec les instructions et les ingrédients ?). Je te propose de creer un exportController qui lui aura une méthode exportBilanPDF() ! PENSE NUTRIMEAL, PENSE GLOBAL !

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/model/BilanSemaine.java
> + */
Tu peux mettre @GETTER et @SETTER en haut de la classe, c'est encore plus concis !

Tu n'as besoin que de mettre ces annotations pour chaque champ que s'il y a au moins un champ ou tu ne veux pas de GETTER SETTER (ce qui est assez rare).

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/model/Ingredient.java
> +@Table(name = "INGREDIENT")
@Entity(name = "nom_de_ma_table") remplace les annotations @Entity et @Table chez toi.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/controller/ExportBilanController.java
> +	@RequestMapping("/bilan/{listeId}/pdf")
Manque javadoc sur cette methode #docnazi <3 D'ailleurs c'est celle que tu as mis dans le home controller qui elle du coup n'a pas de doc. Etourderie ^^

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/model/Ingredient.java
> +	private Long idIngredient;
Nommage des attributs de nos objets : autant je suis d'accord que la colonne id_ingredient est un bon nom pour la table SQL, autant l'attribut dans la classe peut juste s'appeler id .
Ca fait bizarre de dire que dans ton code tu vas faire 

ingredient.getIdIngredient();

au lieu de : 

ingredient.getId();

t'occupes pas de ça, je l'ai déja fait sur ma branche, mais c'était juste pour la reflexion.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/controller/HomeController.java
> +			return new ResponseEntity<>(bilan, HttpStatus.BAD_GATEWAY);
_"The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server."_

C'est pas le bon code Http

En plus en théorie le front va faire tous les contrôles avant de t'envoyer l'objet bilan. Ta méthode n'a aucune raison de planter.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/controller/HomeController.java
> +		if ((bilan != null) && (bilan != null)) {
Un seul controle du null suffira je pense ^^

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/controller/HomeController.java
> +public class HomeController {
Home Controller ? Je ne sais pas si ca a du sens pour une API REST : il faut séparer les choses par sujet. Un recette controller, un bilan controller... Home controller ce serait si on gérait du templating, pour la page d'accueil.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/model/Ingredient.java
> +	@OneToMany(mappedBy="ingredients")
Je sais que je suis chiant sur les détails. Et quand tu vas lire les remarques t'auras surement envie de m'étrangler. Mais pour le mapping franchement GG t'as bien pigé le truc. J'ai pas testé ton code, mais ta solution est élégante.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/model/ListeRecettesBilanSemaine.java
> +public class ListeRecettesBilanSemaine {
Cette classe est inutile : un bilanSemaine pourrait juste avoir 
    une liste de recette qui eux meme ont 
        une liste de recette Ingredient qui eux meme ont 
            une liste d'ingrédients (avec des vitamines et mineraux). 
Ca alourdit le code pour rien (enfin ou j'ai raté un truc dans ton raisonnement c'est possible aussi).

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/service/CalculService.java
> +public class CalculService {
Dans ton architecture, il faut que tu penses à regrouper le code par sujet : les 3 méthodes qui sont ici sont devraient être dans une classe BilanService.
Le service, c'est une classe où on regroupe l'aspect métier en rapport avec un objet / concept (donc techniquement ici y a pas plus métier que de faire les calculs vitamines / minéraux pour un bilan). 
Pose toi la question : tes trois méthodes sont faites pour l'objet BilanSemaine ? Oui. Alors pourquoi les mettre dans un service avec un nom aussi général que CalculService ?

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/service/CalculService.java
> +public BilanSemaine bilanSemaine(String listeIdAsString) throws Exception{
Cette méthode n'est pas optimisé : .

- Enchainement des écrans : le front aura déja chargé les recette du bilan une fois chacune avant de te l'envoyer (étape obligatoire pour que l'user puisse composer son bilan). 
Puis toi ton controller receptionne une liste d'id, que tu parse en Long. Cette liste est utilisée deux fois par tes méthodes calculVita et calculMineraux qui rechargent à chaque fois les recettes qui ont ses id. Au total, avec ce fonctionnement, tu charges chaque recette de la liste 3 fois (1 FRONT 2 BACK). C'est dommage, car une fois suffit : 
Fais en sorte que ton controller receptionne une liste de recette avec @RequestBody (celles qui ont déja été chargé par le front)

```
@RequestMapping(value = "/bilan/new", method = RequestMethod.POST, consumes = "application/json", 
produces = "application/json")
public ResponseEntity<?> createNewBilan(@RequestBody BilanSemaine bilanSemaine) {	

returnedBilan = bilanSemaineService.createBilanSemaine(bilanSemaine);
// return new ReponseEntity<>(returnedBilan, HttpStatus.OK);

}
```

Cf ma remarque sur l'objet ListeRecettesBilanSemaine a supprimer.

Vu que chaque **RECETTE** du bilan contient des **INGREDIENTRECETTE** qui contiennent des **INGREDIENT** qui ont des valeurs **VITAMINES**/**MINERAUX**, tu peux très bien faire tous tes calculs **SANS MEME APPELER LA BASE UNE SEULE FOIS**. Tu peux faire confiance aux données du FRONT puisqu'elles sont déja tirées de la base avant.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/service/ExportBilanPdfService.java
> +public class ExportBilanPdfService {
Même remarque que pour ton exportBilanController : on pourrait avec un exportPDFController et un exportPDFService qui servirait à exporter une recette avec les instructions et ingrédient par exemple. 
Ton exportBilanPDFService devrait devenir une méthode exportBilanToPDF()

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/repository/MethodesPratiquesRepository.java
> +	public List<Long> convertirStringIdEnListeLong(String listeAsString) throws Exception{
CF ma remarque sur ton CalculService, cette méthode n'est pas nécéssaire pour le moment.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/repository/MethodesPratiquesRepository.java
> +	public Double deuxChiffresSignificatifs(Double nombre) {
Par contre cette méthode la elle est cool, et c'est bien de l'avoir génériciser. On en aura surement besoin dans d'autres modules de l'application.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/main/java/com/example/nutrimeal/service/IngredientService.java
> +public class IngredientService {
Manque de la javadoc ! Chaque méthode doit en avoir ! Meme pour des trucs cons comme getIngredientById() Comme ca après qaund Eclipse te propose de générer ta documentation, elle est complète et on peut comprendre l'app rien qu'avec ca en théorie.

2018-04-29 13:38 UTC, clement-bey-cgi commented on src/test/java/com/example/nutrimeal/repository/MethodesPratiquesRepositoryTests.java
> +public class MethodesPratiquesRepositoryTests {
Pour ton problème de test unitaire, j'ai pas trop le temps de me pencher dessus  :'( 

Mais s'ils passent pas gardent les dans un coin mais les push pas sur le master.

2018-04-29 13:39 UTC, closed without merging

2018-05-04 13:45 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/model/Ingredient.java
> +	private Long idIngredient;
Y'a des ID recette, ingredients, instructions et chaque colonne de recette_ingredient

Je préfère spécifier chaque ID pour éviter toute ambiguité, surtout dans l'utilisation de classes intermédiaires (classes résumés etc), mais comme tu veux

2018-05-04 13:46 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/controller/HomeController.java
> +		if ((bilan != null) && (bilan != null)) {
On est jamais trop prudent ! (je changerais ça) mdr xD

2018-05-04 13:49 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/model/ListeRecettesBilanSemaine.java
> +public class ListeRecettesBilanSemaine {
j'ai pas tout compris, mais je zieuterais ça

2018-05-04 13:50 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/service/CalculService.java
> +public class CalculService {
Je souhaite regrouper tout type de calculs dans un seul service, principalement pour éviter des classes de calculs pour chaque onglet

2018-05-04 13:50 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/service/CalculService.java
> +public class CalculService {
Surtout que les calculs sont similaires, on pourra réutiliser des methodes proches ou en modifier, plutot que de dupliquer du code pour un calcul similaire

2018-05-04 13:52 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/repository/MethodesPratiquesRepository.java
> +	public Double deuxChiffresSignificatifs(Double nombre) {
#Science > litéraires.... euh non informaticiens

2018-05-04 13:53 UTC, Shingo76 commented
Merci pour tes retours captain casses couilles ! :)

2018-05-04 13:59 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/controller/HomeController.java
> +		if ((bilan != null) && (bilan != null)) {
En même temps, si le premier est pas null, qui te dis que le 2e.....

2018-05-04 14:01 UTC, Shingo76 commented on src/test/java/com/example/nutrimeal/repository/MethodesPratiquesRepositoryTests.java
> +public class MethodesPratiquesRepositoryTests {
Osef des tests unitaires ! Mon code marche :dancer:

2018-05-04 14:07 UTC, Shingo76 commented on src/main/java/com/example/nutrimeal/service/CalculService.java
> +public BilanSemaine bilanSemaine(String listeIdAsString) throws Exception{
Tu veux dire que pour alimenter la liste de sélection, faut remonter toute les recettes de la base en front, plus les ingredients?
C'est hardcore, mieux vaut juste remonter l'idRecette et le nom de la recette pour le bilan. Faire la requette en base pour <10 recettes après c'est carrément plus léger non?

Rend toi compte, si y'a 1000 recettes en bases, sa fait 1000 recettes + leurs ingrédients stockés dans 6 listes.....    dur